version: 0.0
os: linux
files:
  - source: /
    destination: /www/wwwroot/conect.app
post-update:
  - cd /www/wwwroot/conect.app
  - composer update --no-dev
  - chmod -R 777 /www/wwwroot/conect.app/writable